# Generated by Django 4.2.27 on 2026-05-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0051_ledgerpostingfailure_ledgerreconciliationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='expenses.ledgeraccount'),
        ),
    ]
